language:
  python
python:
  - "3.5"
# command to install dependencies
install:
 - pip install pyyaml
 - pip install coveralls
# command to run tests
script:
  coverage run -m unittest discover -s tests

after_success:
  coveralls