matrix:
  fast_finish: true
  include:
   - language: python
     python: 3.4
     os: linux
   - language: python
     python: 3.5
     os: linux
   - language: generic
     os: osx
install:
- if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      curl -sS https://www.python.org/ftp/python/3.5.2/python-3.5.2-macosx10.6.pkg > python-3.5.2-macosx10.6.pkg;
      sudo installer -pkg python-3.5.2-macosx10.6.pkg -target /;
  fi;
- pip3 install coveralls coverage
- python3 setup.py install
- git clone --branch $TRAVIS_BRANCH https://github.com/missionpinball/mpf-examples.git || git clone --branch `python3 get_version.py` https://github.com/missionpinball/mpf-examples.git || git clone --branch dev https://github.com/missionpinball/mpf-examples.git
- git clone --branch $TRAVIS_BRANCH https://github.com/missionpinball/mpf-mc.git || git clone --branch `python3 get_version.py` https://github.com/missionpinball/mpf-mc.git || git clone --branch dev https://github.com/missionpinball/mpf-mc.git
before_script:
- export PYTHONPATH=$PYTHONPATH:$(pwd)/mpf-mc; 
script:
- python3 -m coverage run -m unittest discover mpf/tests
#- cd mpf-examples/demo_man/ && python3 -m unittest discover -s tests/ && cd ../../
after_success: coveralls

