# config_version=3
# This file contains configuration options for the MPF itself, including
# default settings for your machine-wide game-specific config files.

# You should create specific subfolders for each game you want to make and put
# config files there to override these defaults.

mpf:
    system_modules: !!omap  # order is important here
        - config_processor: mpf.system.config.Config
        - timing: mpf.system.timing.Timing
        - events: mpf.system.events.EventManager
        - mode_controller: mpf.system.mode_controller.ModeController
        - device_manager: mpf.system.device_manager.DeviceManager
        - switch_controller: mpf.system.switch_controller.SwitchController
        - ball_controller: mpf.system.ball_controller.BallController
        - light_controller: mpf.system.light_controller.LightController
        - bcp: mpf.system.bcp.BCP
        - logic_blocks: mpf.system.logic_blocks.LogicBlocks
        - scoring: mpf.system.scoring.ScoreController
        - shot_profile_manager: mpf.system.shot_profile_manager.ShotProfileManager

    device_modules:
        driver.Driver
        switch.Switch
        matrix_light.MatrixLight
        led.LED
        gi.GI
        autofire.AutofireCoil
        ball_device.BallDevice
        playfield.Playfield
        drop_target.DropTarget
        drop_target.DropTargetBank
        shot.Shot
        shot_group.ShotGroup
        flipper.Flipper
        diverter.Diverter
        score_reel.ScoreReel
        score_reel.ScoreReelGroup
        flasher.Flasher
        playfield_transfer.PlayfieldTransfer
        ball_lock.BallLock
        multiball.Multiball
        ball_save.BallSave
    
    plugins:
        auditor
        ball_save
        ball_search
        info_lights
        osc
        socket_events
        switch_player

    paths:
        scriptlets: scriptlets
        shows: shows
        audits: audits/audits.yaml
        machine_files: machine_files
        config: config
        modes: modes

    default_pulse_ms: 10
    default_flash_ms: 50
    auto_create_switch_events: True
    switch_event_active: "%_active"
    switch_event_inactive: "%_inactive"
    switch_tag_event: sw_%
    allow_invalid_config_sections: true
    
    device_events:
        autofire_coils:
            enable: ball_started
            disable: ball_ending, tilt, slam_tilt
        ball_devices:
            request_ball:
            stop:
            eject:
            eject_all:
        ball_locks:
            enable: ball_started
            disable: ball_ending, tilt, slam_tilt
            reset: machine_reset_phase_3
        ball_saves:
            enable:
            disable: ball_ending, tilt, slam_tilt
        diverters:
            enable:
            disable:
            activate:
            deactivate:
        drop_targets:
            reset: ball_starting, machine_reset_phase_3
            knockdown:
        drop_target_banks:
            reset: machine_reset_phase_3, ball_starting
        coils:
            enable:
            disable:
            pulse:
        flashers:
            flash:
        flippers:
            enable: ball_started
            disable: ball_ending, tilt, slam_tilt
            enable_no_hold:
            invert:
        gis:
            enable: machine_reset_phase_3
            disable:
        matrix_lights:
            "on":
            "off":
        multiballs:
            enable: ball_started
            disable: ball_ending, tilt, slam_tilt
            reset: machine_reset_phase_3
            start:
            stop:
        shots:
            enable: ball_started
            disable: ball_ending, tilt, slam_tilt
            reset:
            advance:
            hit:
            remove_active_profile:
        shot_groups:
            enable: ball_started
            disable: ball_ending, tilt, slam_tilt
            reset:
            rotate_left:
            rotate_right:
            enable_rotation:
            disable_rotation:
            advance:
            remove_active_profile:

config_validator:
# values are type|validation|default
    autofire_coils:
        coil: single|self.machine.coils[%]|
        switch: single|self.machine.switches[%]|
        reverse_switch: bool|bool|False
        pulse_ms: int|int|None
        pwm_on_ms: int|int|None
        pwm_off_ms: int|int|None
        coil_action_ms: int|int|None
        delay: int|int|0
        recycle_ms: single|int|125
        debounced: bool|bool|False
        drive_now: bool|bool|False
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    ball_devices:
        exit_count_delay: ms|int|500ms
        entrance_count_delay: ms|int|500ms
        eject_coil: single|self.machine.coils[%]|None
        eject_switch: single|self.machine.switches[%]|None
        entrance_switch: single|self.machine.switches[%]|None
        jam_switch: single|self.machine.switches[%]|None
        eject_count_hold_times: list|ms|None
        confirm_eject_type: single|str|count
        captures_from: single|str|playfield
        eject_targets: list|str|playfield
        # can't convert to objects until all ball_devices are setup
        eject_timeouts: list|ms|None
        confirm_eject_switch: single|self.machine.switches[%]|None
        confirm_eject_event: single|str|None
        balls_per_eject: int|int|1
        max_eject_attempt: int|int|0
        ball_switches: list|self.machine.switches[%]|None
        ball_capacity: int|int|None
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    ball_locks:
        balls_to_lock: int|int|
        lock_devices: list|self.machine.ball_devices[%]|
        source_playfield: single|self.machine.ball_devices[%]|playfield
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    ball_saves:
        source_playfield: single|self.machine.ball_devices[%]|playfield
        auto_disable_time: ms|str|0
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    coils:
        number: single|str|
        number_str: single|str|
        pulse_ms: int|int|0
        holdpatter: single|str|None
        pwm_on: int|int|0
        pwm_off: int|int|0
        allow_enable: bool|bool|False
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    diverters:
        type: single|str|pulse
        activation_time: ms|str|0
        activation_switches: list|self.machine.switches[%]|None
        disable_switches: list|self.machine.switches[%]|None
        deactivation_switches: list|self.machine.switches[%]|None
        activation_coil: single|self.machine.coils[%]|None
        deactivation_coil: single|self.machine.coils[%]|None
        targets_when_active: list|self.machine.ball_devices[%]|playfield
        targets_when_inactive: list|self.machine.ball_devices[%]|playfield
        feeder_devices: list|self.machine.ball_devices[%]|playfield
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    drop_targets:
        switch: single|self.machine.switches[%]|
        reset_coil: single|self.machine.coils[%]|
        knockdown_coil: single|self.machine.coils[%]|None
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    drop_target_banks:
        drop_targets: set|self.machine.drop_targets[%]|
        reset_coil: single|self.machine.coils[%]|None
        reset_coils: list|self.machine.coils[%]|None
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    flashers:
        number: single|str|
        number_str: single|str|
        flash_ms: ms|str|None
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    flippers:
        main_coil: single|self.machine.coils[%]|
        hold_coil: single|self.machine.coils[%]|None
        activation_switch: single|self.machine.switches[%]|
        eos_switch: single|self.machine.switches[%]|None
        use_eos: bool|bool|False
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    gis:
        number: single|str|
        number_str: single|str|
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    leds:
        number: single|str|
        number_str: single|str|
        default_color: single|str|ffffff
        brightness_compensation: list|float|1.0
        fade_ms: int|int|None
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    matrix_lights:
        number: single|str|
        number_str: single|str|
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    multiballs:
        ball_count: int|int|
        source_playfield: single|self.machine.ball_devices[%]|playfield
        shoot_again: ms|str|10s
        ball_locks: list|self.machine.ball_locks[%]|None
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    playfields:
        eject_targets: list|str|None
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    playfield_transfers:
        ball_switch: single|self.machine.switches[%]|
        eject_target: single|self.machine.ball_device[%]|
        captures_from: single|self.machine.ball_devices[%]|
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    score_reels:
        coil_inc: single|self.machine.coils[%]|None
        coil_dec: single|self.machine.coils[%]|None
        rollover: bool|bool|True
        limit_lo: int|int|0
        limit_hi: int|int|9
        repeat_pulse_time: ms|str|200
        hw_confirm_time: ms|str|300
        config: single|str|lazy
        # switch_x is also here but cannot be processed here
    score_reel_groups:
        max_simultaneous_coils: int|int|2
        confirm: single|str|strict
        reels: list|str|
        chimes: list|str|None
        repeat_pulse_time: ms|str|200
        hw_confirm_time: ms|str|300
        config: single|str|lazy
    shots:
        profile: single|str|default
        switch: list|self.machine.switches[%]|None
        switch_sequence: list|self.machine.switches[%]|None
        cancel_switch: list|self.machine.switches[%]|None
        delay_switch: delay_dict|self.machine.switches[%]|None
        lights_when_disabled: bool|bool|True
        time: ms|float|0
        light: list|self.machine.lights[%]|None
        led: list|self.machine.leds[%]|None
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    shot_groups:
        shots: list|self.machine.shots[%]|
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False
    switches:
        number: single|str|
        number_str: single|str|
        type: single|str|NO
        debounce: bool|bool|True
        recycle_time: ticks|str|0
        activation_events: list|str|None
        deactivation_events: list|str|None
        tags: list|str|None
        label: single|str|%
        debug: bool|bool|False

    machine:
        hz: single|int|30
        balls_installed: single|int|1
        min_balls: single|int|1
        glass_off_mode: bool|bool|True

    shot_profiles:
            loop: bool|bool|False
            step_names_to_rotate: list|str|None
            step_names_to_not_rotate: list|str|None
            rotation_pattern: list|str|R
            player_variable: single|str|None
            advance_on_hit: bool|bool|True
            steps:
                name: single|str|
                light_script: single|str|None
                hold: bool|bool|True
                reset: bool|bool|False
                

# Default settings for machines. All can be overridden

machine:
    balls_installed: 1
    min_balls: 1
    glass_off_mode: true

timing:
    hz: 30
    hw_thread_sleep_ms: 1

hardware:
    platform: virtual
    coils: default
    switches: default
    matrix_lights: default
    leds: default
    dmd: default
    gis: default
    flashers: default

p_roc:
    lamp_matrix_strobe_time: 100
    watchdog_time: 1000
    use_watchdog: True

fast:
    baud: 921600
    watchdog: 1s
    default_debounce_close: 10ms
    default_debounce_open: 30ms

modes:
    - attract
    - game


led_settings:
    brightness_compensation: 1.0
    default_led_fade_ms: 100
    gamma: 2.5
    whitepoint: 1.0, 1.0, 1.0
    linear_slope: 1.0
    linear_cutoff: 0.0
    keyframe_interpolation: True
    dithering: True

game:
    balls_per_game: 3
    max_players: 4

auditor:
    save_events:
        game_started
        ball_ended
        game_ended
    num_player_top_records: 10
    audit:
        shots
        switches
        events
        player
    events:
        ball_search_begin_phase1
        game_started
        game_ended
    player:
        score

ball_search:
    Secs until ball search start: 10
    Secs between ball search rounds: 3
    Secs between ball search coils: .15
    If ball search fails: Keep Looking

logic_blocks:

    counters:

        tilt:
            count_events: sw_tilt
            event_when_hit: tilt_hit
            count_complete_value: 3
            events_when_complete: tilt
            multiple_hit_window: 500ms
            reset_each_ball: yes

        slam_tilt:
            count_events: sw_slamTilt
            count_complete_value: 1
            events_when_complete: slam_tilt

displaydefaults:
    text:
        font: default
        size: 10
        opaque: false
        v_pos: center
        h_pos: center
        x: 0
        y: 0
        time: 0s
        text_color: ffffff
        background_color: 000000
        text_shade: 15
        background_shade: 0
        antialias: False

fonts:
    default:
        file: Quadrit.ttf
        size: 10
        crop_top: 2
        crop_bottom: 3
    space title huge:
        file: DEADJIM.TTF
        size: 29
        antialias: yes
        crop_top: 3
        crop_bottom: 3
    space title:
        file: DEADJIM.TTF
        size: 21
        antialias: yes
        crop_top: 2
        crop_bottom: 3
    medium:
        file: pixelmix.ttf
        size: 8
        crop_top: 1
        crop_bottom: 1
    small:
        file: smallest_pixel-7.ttf
        size: 9
        crop_top: 2
        crop_bottom: 3
    tall title:
       file: big_noodle_titling.ttf
       size: 20

textstrings:
    volume_zero: OFF
    volume_max: MAX

asset_defaults:
    shows:
        default:
            load: preload

bcp:
    connections:
        local_display:
            host: localhost
            port: 5050
            connection_attempts: 5
            require_connection: no

    event_map:
        ball_started:
            command: ball_start
            params:
                player: "%player"
                ball: "%ball"

        ball_ending:
            command: ball_end

        attract_start:
            command: attract_start

        attract_stop:
            command: attract_stop

        game_ended:
            command: game_end

        player_turn_start:
            command: player_turn_start
            params:
                player: "%number"

    player_variables:
      __all__

volume:
    tracks:
        master: 20
        voice: 20
        sfx: 20
        music: 20
    steps: 20

open_pixel_control:
    host: localhost
    port: 7890
    connection_required: no
    connection_attempts: -1
    number_format: int

triggers:
    assets_to_load:
        bcp_name: assets_to_load
        params:
            assets: "%assets"
    assets_loading_complete:
        bcp_name: assets_loading_complete

shot_profiles:
    default:
        steps:
          - name: unlit
            light_script: "off"
          - name: lit
            light_script: "on"

light_scripts:
    flash:
        - tocks: 1
          color: ff
        - tocks: 1
          color: 0
    "on":
        - tocks: 1
          color: ff
    "off":
        - tocks: 1
          color: 0

playfields:
    playfield:
        tags: default