# config_version=1
# This file contains confinguration options for the MPF itself, including
# default settings for your pinball machines.

# You should create specific subfolders for each game you want to make and put
# config files there to override these defaults.


# Configuration for the MPF framework itself

mpf:
    system_modules: !!omap  # order is important here
        - timing: mpf.system.timing.Timing
        - events: mpf.system.events.EventManager
        - switch_controller: mpf.system.switch_controller.SwitchController
        - ball_controller: mpf.system.ball_controller.BallController
        - modes: mpf.system.modes.ModeController
        - light_controller: mpf.system.light_controller.LightController
        - bcp: mpf.system.bcp.BCP
        - shots: mpf.system.shots.ShotController
        - logic_blocks: mpf.system.logic_blocks.LogicBlocks
        - scoring: mpf.system.scoring.ScoreController

    device_modules:
        driver.Driver
        switch.Switch
        matrix_light.MatrixLight
        led.LED
        gi.GI
        autofire.AutofireCoil
        ball_device.BallDevice
        drop_target.DropTarget
        drop_target.DropTargetBank
        target.Target
        target.TargetGroup
        rollover.Rollover
        rollover.RolloverGroup
        flipper.Flipper
        diverter.Diverter
        score_reel.ScoreReel
        score_reel.ScoreReelGroup
        flasher.Flasher
        playfield_transfer.PlayfieldTransfer
    
    plugins:
        auditor
        ball_save
        ball_search
        info_lights
        osc
        socket_events
        switch_player

    paths:
        scriptlets: scriptlets
        shows: shows
        audits: audits/audits.yaml
        machine_files: machine_files
        config: config
        modes: modes

    default_pulse_ms: 10
    default_flash_ms: 50
    auto_create_switch_events: True
    switch_event_active: "%_active"
    switch_event_inactive: "%_inactive"
    switch_tag_event: sw_%

# Default settings for machines. All can be overridden

machine:
    Balls Installed: 1
    Min Balls: 1
    Max Balls: 10

timing:
    hz: 30
    hw_thread_sleep_ms: 1

hardware:
    platform: virtual
    coils: default
    switches: default
    matrixlights: default
    leds: default
    dmd: default
    gis: default
    flashers: default

p_roc:
    lamp_matrix_strobe_time: 100
    watchdog_time: 1000
    use_watchdog: True

fast:
    baud: 921600
    watchdog: 1s
    default_debounce_close: 10ms
    default_debounce_open: 30ms


ledsettings:
    brightness_compensation: 1.0
    default_led_fade_ms: 100
    gamma: 2.5
    whitepoint: 1.0, 1.0, 1.0
    linear_slope: 1.0
    linear_cutoff: 0.0
    keyframe_interpolation: True
    dithering: True

game:
    Balls per game: 3
    Max players per game: 4

machineflow:
    mpf.game.attract.Attract
    mpf.game.game.Game

auditor:
    save_events:
        game_started
        ball_ended
        game_ended
    num_player_top_records: 10
    audit:
        shots
        switches
        events
        player
    events:
        ball_search_begin_phase1
        game_started
        game_ended
    player:
        score

ballsearch:
    Secs until ball search start: 10
    Secs between ball search rounds: 3
    Secs between ball search coils: .15
    If ball search fails: Keep Looking

logicblocks:

    counters:

        tilt:
            count_events: sw_tilt
            event_when_hit: tilt_hit
            count_complete_value: 3
            events_when_complete: tilt
            multiple_hit_window: 500ms
            reset_each_ball: yes

        slam_tilt:
            count_events: sw_slamTilt
            count_complete_value: 1
            events_when_complete: slam_tilt

displaydefaults:
    text:
        font: default
        size: 10
        opaque: false
        v_pos: center
        h_pos: center
        x: 0
        y: 0
        time: 0s
        text_color: ffffff
        background_color: 000000
        text_shade: 15
        background_shade: 0
        antialias: False

fonts:
    default:
        file: Quadrit.ttf
        size: 10
        crop_top: 2
        crop_bottom: 3
    space title huge:
        file: DEADJIM.TTF
        size: 29
        antialias: yes
        crop_top: 3
        crop_bottom: 3
    space title:
        file: DEADJIM.TTF
        size: 21
        antialias: yes
        crop_top: 2
        crop_bottom: 3
    medium:
        file: pixelmix.ttf
        size: 8
        crop_top: 1
        crop_bottom: 1
    small:
        file: smallest_pixel-7.ttf
        size: 9
        crop_top: 2
        crop_bottom: 3
    tall title:
       file: big_noodle_titling.ttf
       size: 20

textstrings:
    volume_zero: OFF
    volume_max: MAX

assetdefaults:
    shows:
        default:
            load: preload

bcp:
    connections:
        local_display:
            host: localhost
            port: 5050
            connection_attempts: 5
            require_connection: no

    event_map:
        ball_started:
            command: ball_start
            params:
                player: "%player"
                ball: "%ball"

        ball_ending:
            command: ball_end

        machineflow_Attract_start:
            command: attract_start

        machineflow_Attract_stop:
            command: attract_stop

        game_ended:
            command: game_end

        player_turn_start:
            command: player_turn_start
            params:
                player: "%number"
    
    player_variables:
#        __all__
        ball
        extra_balls

volume:
    tracks:
        master: 20
        voice: 20
        sfx: 20
        music: 20
    steps: 20

openpixelcontrol:
    host: localhost
    port: 7890
    connection_required: no
    connection_attempts: -1
    number_format: int

triggers:
    assets_to_load:
        bcp_name: assets_to_load
        params:
            assets: "%assets"
    assets_loading_complete:
        bcp_name: assets_loading_complete
