Images:
    scribble:
        file: scribble.bmp
        alpha_color: 0
        target: dmd
    p_roc:
        file: p_roc.dmd
        alpha_color: 0
    #mpf_background:
    #    file: mpf_background_800_600.bmp

Animations:
    rolling_ball:
        file: rolling_ball.dmd
        alpha_color: 15

Sounds:
    intro_loop:
        channel: music
        volume_offset: 0
        file: waiting to plunge loop.ogg
        preload: True
    slingshot:
        channel: sfx
        file: slingshot.ogg
    ball_launch_motorcycle:
        file: ball launch motorcycle.ogg
    main_loop:
        file: main song loop.ogg