Images:
    scribble:
        file: scribble.bmp
        alpha_color: 0
        target: dmd
    p_roc:
        file: p_roc.dmd
        alpha_color: 0
    #mpf_background:
    #    file: mpf_background_800_600.bmp

Animations:
    rolling_ball:
        file: rolling_ball.dmd
        alpha_color: 15

Sounds:
    music:
        intro_loop:
            volume: 1
            file: waiting to plunge loop.ogg
            preload: True
    
    sfx:
        slingshot:
            file: slingshot.ogg
            priority: 0
            max_queue_time: 100ms
            preload: yes
        ball_launch_motorcycle:
            file: ball launch motorcycle.ogg
        main_loop:
            file: main song loop.ogg
    
    voice:
        

