Images:
    p_roc:
        file: p_roc.dmd
        alpha_color: 0

Animations:
    rolling_ball:
        file: rolling_ball.dmd
        alpha_color: 15

#Movies:
#    torch_background:
#        file: torches.mpg