Scriptlets:
    attract.Attract
    deadworld.Deadworld
    add_a_ball.AddABall

Plugins:
    - shots.ShotController
    - ball_search.BallSearch
    - logic_blocks.LogicBlocks
    - scoring.ScoreController
    - auditor.Auditor
    - bcp.BCP

Config:
    - dmd.yaml
    - game_logic.yaml
    - hardware.yaml
    - languages.yaml
    - sound.yaml
    - window.yaml
