# Instructions for this config file:
# https://missionpinball.com/docs/configuration-file-reference/
Config:
    # https://missionpinball.com/docs/configuration-file-reference/config/
    - machine.yaml
    - devices.yaml
    - game.yaml
    - textstrings.yaml
    - keymap.yaml
    - shots.yaml

Language: en