Scriptlets:
    attract.Attract
    deadworld.Deadworld
    add_a_ball.AddABall

Plugins:
    - ball_search.BallSearch
    - auditor.Auditor

Config:
    - dmd.yaml
    - game_logic.yaml
    - hardware.yaml
    - languages.yaml
    - sound.yaml
    - window.yaml
