# Instructions for this config file:
# https://missionpinball.com/docs/configuration-file-reference/


    
MachineFlow:
    mpf.game.attract.Attract
    mpf.game.game.Game

BallSearch:
    Secs until ball search start: 10
    Secs between ball search rounds: 3
    Secs between ball search coils: .15
    Total search time: 20
    If ball search fails: continue

    Phase 1 secs: 10
    Phase 2 secs: 10
    Missing balls on startup: ignore # search, halt #todo

Game:
    num_hits_for_valid_playfield: 2
    Balls per game: 1
    Max players per game: 4

Scriptlets:
    attract.Attract
    deadworld.Deadworld

Plugins:
    keyboard.Keyboard
    lcd.LCD
    ball_search.BallSearch
    event_triggers.EventTriggers

EventTriggers:
    tilt:
        trigger_events: tilt
        event_when_hit: tilt_hit
        hits_to_complete: 3
        multiple_hit_window: 500ms
        enable_events:
        disable_events:
        reset_events: ball_ending
        event_when_complete: tilt
        settle_time: 5s
    slam_tilt:
        switch_tags: slam_tilt
        hits_to_tile: 1


LCD:
    width: 800
    height: 600
    title: Judge Dredd
    items:
        score
        player
        ball
        version
        looprate

Actions:
    
    steps:
        event1
        (event2 or event1) and event3
        