Game:
    Balls per game: 2
    Max players per game: 4
    player_controlled_eject_tag: right_eject

Modes:
    - skillshot
    - base
    - both_ramps_made

ShowPlayer:
    machineflow_Attract_start:
      - show: drop_target_sweep
        repeat: yes
        tocks_per_sec: 5
      - show: chain_sweep
        repeat: yes
        tocks_per_sec: 8
      - show: flipper_area_flash
        repeat: yes
        tocks_per_sec: 4
      - show: lock_sweep
        repeat: yes
        tocks_per_sec: 5
      - show: crime_sweep
        repeat: yes
        tocks_per_sec: 5
      - show: perp_sweep
        repeat: yes
        tocks_per_sec: 3
      - show: random_blinking
        repeat: yes
        tocks_per_sec: 4
      - show: attract_display
        repeat: yes
        tocks_per_sec: 1

    machineflow_Attract_stop:
      - show: drop_target_sweep
        action: stop
      - show: chain_sweep
        action: stop
      - show: flipper_area_flash
        action: stop
      - show: lock_sweep
        action: stop
      - show: crime_sweep
        action: stop
      - show: perp_sweep
        action: stop
      - show: random_blinking
        action: stop
      - show: attract_display
        action: stop

Shots:
    RightRamp:
        Switch: rightRampExit
    LeftRamp:
        Type: Sequence
        Switches: leftRampEnter, leftRampExit
        Time: 3s
    LeftOrbit:
        Type: Sequence
        Switches: leftRollover, topRightOpto
        Time: 3s
    WeakRightOrbit:
        Type: Sequence
        Switches: topRightOpto, topCenterRollover
        Time: 3s
    FullRightOrbit:
        Type: Sequence
        Switches: topRightOpto, leftRollover
        Time: 3s
    AirRaidRamp:
        Switch: topRampExit
    OrangeStandups:
        Switch: threeBankTargets
    Slingshot:
        Switch: slingR, slingL
    Inlane:
        Switch: inlaneL, inlaneR, outerInlaneR
    Outlane:
        Switch: outlaneR, outlaneL
    DropTarget:
        Switch: dropTargetJ, dropTargetU, dropTargetD, dropTargetG, dropTargetE

SlidePlayer:
    volume_change:
        type: Text
        text: "VOLUME: %display_volume"

