# Instructions for this config file:
# https://missionpinball.com/docs/configuration-file-reference/


    
MachineFlow:
    mpf.game.attract.Attract
    mpf.game.game.Game

BallSearch:
    Secs until ball search start: 10
    Secs between ball search rounds: 3
    Secs between ball search coils: .15
    Total search time: 20
    If ball search fails: continue

    Phase 1 secs: 10
    Phase 2 secs: 10
    Missing balls on startup: ignore # search, halt #todo

Game:
    num_hits_for_valid_playfield: 2
    Balls per game: 3
    Max players per game: 4

Hacklets:
    attract.Attract

Plugins:
    keyboard.Keyboard
    window.Window
    ball_search.BallSearch

Window:
    width: 800
    height: 600
    title: Judge Dredd
    items:
        score
        player
        ball
        version