# Instructions for this config file:
# https://missionpinball.com/docs/configuration-file-reference/

MachineFlow:
    mpf.game.attract.Attract
    mpf.game.game.Game

BallSearch:
    Secs until ball search start: 10
    Secs between ball search rounds: 3
    Secs between ball search coils: .15
    Total search time: 20
    If ball search fails: continue

    Phase 1 secs: 10
    Phase 2 secs: 10
    Missing balls on startup: ignore # search, halt #todo

Game:
    num_hits_for_valid_playfield: 2
    Balls per game: 3
    Max players per game: 4
    Max extra balls stacked: unlimited
    Max extra balls per game: unlimited
    player_controlled_eject_tag: right_eject

Scriptlets:
    attract.Attract
    deadworld.Deadworld
    jd_game.JDGame

Plugins:
    shots.ShotController
    keyboard.Keyboard
    ball_search.BallSearch
    logic_blocks.LogicBlocks
    scoring.ScoreController
    auditor.Auditor
    info_display.InfoDisplay
    sound.SoundController

DMD:
    physical: True
    width: 128
    height: 32
    shades: 16
    fps: auto #todo

Window:
    width: 800
    height: 600
    title: Mission Pinball Framework
    resizeable: yes
    frame: yes
    fullscreen: no
    fps: 3
    quit_on_close: True
    background_image: mpf/images/mpf_background_800_600.jpg
    elements:
        DMD:
            width: 512
            height: 128
            boarder_width: 2
            boarder_color: 333333
            h_pos: center
            v_pos: center
            pixel_color: ff6600
            dark_color: 000000
        LightMap:
            width: 100
            height: 400