Sound:
    channels:
        voice:
            volume_offset: 0
            priority: 2
        sfx:
            volume_offset: 0
            priority: 1
            ducking: -5
        music:
            volume_offset: 0
            priority: 0
            ducking: -10
            type: streaming

    buffer: 256
    #bits: 16  # negative for signed
    #frequency: 22050
    initial_volume: 50
    volume_steps: 20

Sounds:
    intro_loop:
        channel: music
        volume_offset: 0
        file: waiting to plunge loop.ogg
        preload: True
    slingshot:
        channel: sfx
        file: slingshot.ogg
    ball_launch_motorcycle:
        file: ball launch motorcycle.ogg
    main_loop:
        file: main song loop.ogg

GameSounds:
    pluger_lane_ball_start:
        sound: intro_loop
        start_events: ball_starting
        stop_events: ball_live_added
        duration:
        loops: -1
        priority:
        fade_in: 0
        fade_out: 0
        channel: music
        volume_offset: 0
    ball_launch_motorcycle:
        sound: ball_launch_motorcycle
        start_events: balldevice_shooterLaneR_ball_eject_attempt
    slingshot:
        sound: slingshot
        start_events: shot_Slingshot
    main_loop:
        sound: main_loop
        start_events: ball_live_added
        loops: -1
        stop_events: machineflow_Game_stop
        