Sound:
    channels:
        voice:
            volume_offset: 0
            priority: 2
        sfx:
            volume_offset: 0
            priority: 1
            ducking: -5
        music:
            volume_offset: 0
            priority: 0
            ducking: -10
            type: streaming

    buffer: 256
    #bits: 16  # negative for signed
    #frequency: 22050
    initial_volume: 50
    volume_steps: 20