Language:
    en:
        left_flipper_button: Left Flipper Button
        light: Light
        replay: Replay
        coil: Coil
        switch: Switch
        credit: Credit
        extra_ball: Extra Ball
        special: Special
        flipper: Flipper
        ball: Ball
        game_over: Game Over
        shoot_again: Shoot Again
        player_1: Player 1
        player_2: Player 2
        player_3: Player 3
        player_4: Player 4
        tilt: Tilt
        magnet: Magnet
        standup: Standup
        drop_target: Drop Target
        relay: Relay  # The electrical kind
        start: Start
        press_start_button: Press Start Button
        insert_coins: Insert Coins
