# config_version=2
Config:
    - config.yaml

switch_player:
    start_event: machine_reset_phase_3
    start_delay: 1s
    steps:
      - time: 100ms
        switch: s_trough_1
        action: activate
      - time: 600ms
        switch: s_start
        action: hit
      - time: 100ms
        switch: s_trough_1
        action: deactivate
      - time: 1s
        switch: s_shooter_lane
        action: activate
      - time: 1s
        switch: s_ball_launch
        action: hit
      - time: 100ms
        switch: s_shooter_lane
        action: deactivate
      - time: 1s
        switch: s_upper_left_flipper_gate
        action: hit
      - time: 1s
        switch: s_left_loop
        action: hit
      - time: 1s
        switch: s_right_inlane
        action: hit
      - time: 500ms
        switch: s_start
        action: hit
      - time: 2.5s
        switch: s_trough_1
        action: activate
      - time: 1s
        switch: s_trough_1
        action: deactivate
      - time: 1s
        switch: s_shooter_lane
        action: activate
      - time: 1s
        switch: s_ball_launch
        action: hit
      - time: 100ms
        switch: s_shooter_lane
        action: deactivate
      - time: 200ms
        switch: s_right_inlane
        action: hit
      - time: 200ms
        switch: s_right_inlane
        action: hit
      - time: 200ms
        switch: s_right_inlane
        action: hit
      - time: 2.5s
        switch: s_trough_1
        action: activate