# config_version=3

config:
    - hardware.yaml
    - shots.yaml
    - keyboard.yaml

mpf:
  default_pulse_ms: 20

game:
    balls_per_game: 3
    max_players: 4
#    player_controlled_eject_tag: plunger

modes:
  - base
  - claw_lit_for_major_mode
  - mode1_acmag
  - skillshot
  - bonus
  - high_score
  - tilt
  - credits

scriptlets:
    add_a_ball.AddABall
    claw.Claw

images:
    demo_man_logo:
        target: dmd

