# config_version=2

config:
    - hardware.yaml

mpf:
  default_pulse_ms: 20

game:
    balls per game: 3
    max players per game: 4
    player_controlled_eject_tag: plunger

modes:
  - base
  - claw_lit_for_major_mode
  - mode1_acmag
  - skillshot

scriptlets:
    attract.Attract
    add_a_ball.AddABall
    claw.Claw



shots:
    left_orbit:
        Type: Sequence
        Switches: s_upper_left_flipper_gate, s_left_loop
        Time: 3s
    left_ramp:
        Type: Sequence
        Switches: s_left_ramp_enter, s_left_ramp_exit
        Time: 3s
    side_ramp:
        Type: Sequence
        Switches: s_side_ramp_enter, s_side_ramp_exit
        Time: 3s
    right_ramp:
        Type: Sequence
        Switches: s_right_ramp_enter, s_right_ramp_exit
        Time: 3s
    right_orbit:
        Type: Sequence
        Switches: s_right_freeway, s_left_loop, s_upper_left_flipper_gate,
        Time: 3s
    center_ramp:
        Switch: s_center_ramp

slide_player:
    volume_change:
        type: Text
        text: "VOLUME: %display_volume"
        expire: 2s
        slide_priority: 10000
    assets_to_load:
        type: text
        text: "LOADING ASSETS: %assets TO GO"
        font: small
    assets_loading_complete:
        type: text
        text: ASSET LOADING COMPLETE
        font: small

images:
    demo_man_logo:
        target: dmd

