Machine:
    HZ: 30
    Balls Installed: 1
    Min Balls: 0
    Max Balls: 1

Hardware:
    Platform: fast
    DriverBoards: fast

Scriptlets:
    attract.Attract
    game.Game

Fast:
    port0_name: COM9
    port0_baud: 921600
    port1_name: COM8
    port1_baud: 460800
    main_port: 0
    led_port: 1
    dmd_port: 1
    config_number_format: hex

Game:
    Balls per game: 3
    Max players per game: 4
    Restart on long press: False
    Allow start with loose balls: False

MachineFlow:
    mpf.game.attract.Attract
    mpf.game.game.Game

Plugins:
    osc.OSC
    logic_blocks.LogicBlocks
    auditor.Auditor
    info_display.InfoDisplay
    shots.ShotController
    scoring.ScoreController

OSC:
    machine_ip: auto
    machine_port: 8000
    approved_client_ips: any
    client_port: 9000
    debug_messages: false
    client_updates:
        switches
        data

Display:
    dmd.DMD:
        width: 128
        height: 32
        timing_list: 50, 70, 90, 200
        color_depth: 4
        refresh_ratio: 1
    virtual_dmd.VirtualDMD:
        width: 128
        height: 32
        color_depth: 4
        refresh_ratio: 10
        color_map:
            0: 000000
            1: 110000
            2: 220000
            3: 330000
            4: 440000
            5: 550000
            6: 660000
            7: 770000
            8: 880000
            9: 990000
            10: aa0000
            11: bb0000
            12: cc0000
            13: dd0000
            14: ee0000
            15: ff0000

MatrixLights:
    dummy:
        number: 0

Switches:
    leftPop:
        number: 0
    rightPop:
        number: 1
    bottomPop:
        number: 2
    leftOutlane:
        number: 3
    rightOutlane:
        number: 4
    leftInlane:
        number: 5
    rightInlane:
        number: 6
    leftFlipper:
        number: 8
        tags: left_flipper
    rightFlipper:
        number: a
        tags: right_flipper
    start:
        tags: start
        number: b
    rightSling:
        number: c
    leftSling:
        number: d
    ballLock:
        number: e
    trough:
        number: f
    topLaneLeft:
        number: 10
    topLaneMiddle:
        number: 11
    topLaneRight:
        number: 12
    spinner:
        number: 13
    leftOrbit:
        number: 14
    standupTopLeft:
        number: 15
    standupMidLeft2:
        number: 16
    standupMidLeft1:
        number: 17
    standupMiddle:
        number: 18
    standupMidRight2:
        number: 19
    standupMidRight1:
        number: 1a

Coils:
    leftPop:
        number: 0
        pulse_ms: 20
    rightPop:
        number: 1
        pulse_ms: 20
    bottomPop:
        number: 2
        pulse_ms: 20
    leftFlipperMain:
        number: 8
        pulse_ms: 30
    leftFlipperHold:
        number: 9
    rightFlipperMain:
        number: a
        pulse_ms: 30
    rightFlipperHold:
        number: b
    rightSling:
        number: c
        pulse_ms: 9
    leftSling:
        number: d
        pulse_ms: 9
    ballLock:
        number: e
        pulse_ms: 20
    trough:
        number: f
        pulse_ms: 40

LEDs:
    leftOrbit:
        number: 0
    leftUpperStandup:
        number: 1
    upperLaneLeft:
        number: 2
    upperRolloverLeft:
        number: 3
    upperLaneMiddle:
        number: 4
    upperRolloverMiddle:
        number: 5
    upperLaneRight:
        number: 6
    upperRolloverRight:
        number: 7
    locklaneTop:
        number: 8
    locklane1:
        number: 9
    locklane2:
        number: a
    locklane3:
        number: b
    locklane4:
        number: c
    locklane5:
        number: d
    semicircle10:
        number: e
    righttarget1:
        number: f
    righttarget2:
        number: 10
    centerRow5:
        number: 11
    centerRow4:
        number: 12
    centerRow3:
        number: 13
    centerRowRed:
        number: 14
    centerRow2:
        number: 15
    centerRow1:
        number: 16
    spinnerArrow:
        number: 17
    lefttarget2:
        number: 18
    lefttarget1:
        number: 19
    leftoutlane:
        number: 1a
    semicircle1:
        number: 1b
    semicircle2:
        number: 1c
    semicircle3:
        number: 1d
    semicircle4:
        number: 1e
    semicircle5:
        number: 1f
    shootAgain:
        number: 20
    semicircle_above:
        number: 21
    semicircle6:
        number: 22
    semicircle7:
        number: 23
    semicircle8:
        number: 24
    semicircle9:
        number: 25
    leftoutlane:
        number: 26

BallDevices:
    trough:
        tags: trough, home, drain, ball_add_live
        ball_switches: trough
        entrance_count_delay: 200ms
        exit_count_delay: 1s
        eject_coil: trough
        eject_switch: trough
        confirm_eject_type: count    
    
    ballLock:
        ball_switches: ballLock
        entrance_count_delay: 200ms
        exit_count_delay: 1s
        eject_coil: ballLock
        eject_switch: ballLock
        confirm_eject_type: count

Flippers:
    Left:
        main_coil: leftFlipperMain
        hold_coil: leftFlipperHold
        activation_switch: leftFlipper
    Right:
        main_coil: rightFlipperMain
        hold_coil: rightFlipperHold
        activation_switch: rightFlipper

Autofire Coils:
    leftPop:
        coil: leftPop
        switch: leftPop
    rightPop:
        coil: rightPop
        switch: rightPop
    bottomPop:
        coil: bottomPop
        switch: bottomPop
    leftSling:
        coil: leftSling
        switch: leftSling
    rightSling:
        coil: rightSling
        switch: rightSling

Targets:
    laneLeft:
        switch: topLaneLeft
        light: upperLaneLeft
    laneMiddle:
        switch: topLaneMiddle
        light: upperLaneMiddle
    laneRight:
        switch: topLaneRight
        light: upperLaneRight
    left1:
        light: lefttarget1
        switch: standupMidLeft1
    left2:
        light: lefttarget2
        switch: standupMidLeft2
    right1:
        light: righttarget1
        switch: standupMidRight1
    right2:
        light: righttarget2
        switch: standupMidRight2
    middle:
        light: centerRowRed
        switch: standupMiddle
    upperLeft:
        switch: standupTopLeft
        light: leftUpperStandup
    spinner:
        light: spinnerArrow
        switch: spinner
        reset_events:
            target_spinner_unlit_hit: 30ms

TargetGroups:
    upperLanes:
        targets: laneLeft, laneMiddle, laneRight
        rotate_left_events: sw_left_flipper
        rotate_right_events: sw_right_flipper
        reset_events: targets_upperLanes_lit_complete

Shots:
    pops:
        Switch: leftPop, rightPop, bottomPop
    slings:
        Switch: leftSling, rightSling

Scoring:
    targets_upperLanes_lit_complete:
        Score: 5000
    targets_upperLanes_lit_hit:
        Score: 100
    targets_upperLanes_unlit_hit:
        Score: 1000
    shot_pops:
        Score: 150
    shot_slings:
        Score: 10
    balldevice_ballLock_ball_enter:
        Score: 2500
    target_right1_lit:
        Score: 50
    target_right2_lit:
        Score: 50
    target_left1_lit:
        Score: 50
    target_left2_lit:
        Score: 50
    target_middle_lit:
        Score: 50
    target_upperLeft_lit:
        Score: 50
    target_right1_unlit:
        Score: 50
    target_right2_unlit:
        Score: 250
    target_left1_unlit:
        Score: 250
    target_left2_unlit:
        Score: 250
    target_middle_unlit:
        Score: 250
    target_upperLeft_unlit:
        Score: 250