#config_version=3
mode:
  code: tilt.Tilt
  priority: 10000
  start_events: machine_reset_phase_3
  stop_on_ball_end: False

slide_player:
  tilt_warning_1:
    type: text
    text: WARNING
    expire: 1s
  tilt_warning_2:
    - type: text
      text: WARNING
      y: 2
    - type: text
      text: WARNING
      y: 18
      expire: 1s
  tilt:
    type: text
    text: TILT
  tilt_clear:
    clear_slides: yes
