#config_version=3
mode:
  code: credits.Credits
  priority: 11000
  start_events: machine_reset_phase_3
  stop_events:

credits:
  max_credits: 12
  free_play: no
  service_credits_switch: s_esc
  switches:
    - switch: s_left_coin
      type: money
      value: .25
    - switch: s_center_coin
      type: money
      value: .25
    - switch: s_right_coin
      type: token
      value: 1
    - switch: s_fourth_coin
      value: 1
      type: money
  pricing_tiers:
    - price: .50
      credits: 1
    - price: 2
      credits: 5
  fractional_credit_expiration_time: 15m
  credit_expiration_time: 2h
  persist_credits_while_off_time: 1h

  # timestamp in audits
  # earnings data file?

slide_player:
  credits_added:
    type: text
    text: "%machine|credits_string%"
    expire: 2s
  not_enough_credits:
  - type: text
    text: "%machine|credits_string%"
    expire: 2s
    font: small
    v_pos: bottom
  - type: text
    text: INSERT COINS
    decorators:
      type: blink
      repeats: -1
      on_secs: .2
      off_secs: .2