Mode:
    start_events: both_ramps_made
    stop_events: ball_ending
    priority: 200
    type: timed
    timer_secs: 30
    timer_start_events:
    timer_pause_events:
    timer_start_paused: No

Scoring:
    shot_RightRamp:
        Score: 50000
        Block: yes
    shot_LeftRamp:
        Score: 50000
        Block: yes

SlidePlayer:
    mode_both_ramps_made_started:
      - type: Text
        text: SHOOT RAMP FOR 50K