# Instructions for this config file:
# https://missionpinball.com/docs/configuration-file-reference/


    
GameFlow:
    - attract:
        Module: mpf.attract
        Class: Attract
    - game:
        Module: mpf.game
        Class: Game

BallSearch:
    Secs until ball search start: 10
    Secs between ball search rounds: 3
    Secs between ball search coils: .15
    Total search time: 20
    If ball search fails: continue

    Phase 1 secs: 10
    Phase 2 secs: 10
    Missing balls on startup: ignore # search, halt #todo

Game:
    num_hits_for_valid_playfied: 2
    Balls per game: 3
    Max players per game: 4