# Mission Pinball Framework machine configuration file for William Star Trek: The
# Next Generation

# Instructions for this config file:
# https://missionpinball.com/docs/configuration-file-reference/

# Created by Brian Madden & Gabe Knuth

OSC:
    machine_ip: 127.0.0.1

Scriptlets:
    attract.Attract
    game.Game

Plugins:
    - osc.OSC
    - auditor.Auditor
    - logic_blocks.LogicBlocks
    - auditor.Auditor
    - shots.ShotController
    - scoring.ScoreController
    - sound.SoundController

Config:
    - hardware.yaml
    - game_logic.yaml
    - dmd.yaml
    - assets.yaml

