#config_version=4
mode:
  code: service.Service
  priority: 100000
  start_events: reset_complete
  stop_on_ball_end: False

event_player:
    sw_service_door_open_active:
        - service_door_opened
    sw_service_door_open_inactive:
        - service_door_closed
    sw_power_off_inactive:
        - service_power_on
    sw_power_off_active:
        - service_power_off

sound_player:
    service_power_off: power_off

slide_player:
  service_door_opened:
    service_door_open:
      action: play
  service_door_closed:
    service_door_open:
      action: remove

  service_menu_show:
    service_menu:
      action: play
      priority: 1
  service_menu_hide:
    service_menu:
      action: remove

  service_switch_test_start:
    service_switch_test:
      action: play
      priority: 2
  service_switch_test_stop:
    service_switch_test:
      action: remove


widget_player:
  service_power_off:
    service_power_off_door_open:
      action: add
      slide: service_door_open
  service_power_on:
    service_power_off_door_open:
      action: remove
      slide: service_door_open

  service_menu_deselected:
    service_menu_item_switch:
      action: remove
      slide: service_menu
    service_menu_item_coil:
      action: remove
      slide: service_menu
    service_menu_item_settings:
      action: remove
      slide: service_menu
  service_menu_selected_switch:
    service_menu_item_switch:
      action: add
      slide: service_menu
  service_menu_selected_coil:
    service_menu_item_coil:
      action: add
      slide: service_menu
  service_menu_selected_settings:
    service_menu_item_settings:
      action: add
      slide: service_menu


slides:
  service_door_open:
  - type: text
    text: Door Open
    style: medium
    anchor_y: bottom
    x: center
    y: bottom+21
  - type: text
    text: Press enter for service
    style: small
    anchor_y: bottom
    x: center
    y: bottom+12
  service_menu:
  - type: text
    text: Service Menu
    style: small
    anchor_y: top
    x: center
    y: top
  service_switch_test:
  - type: text
    text: Switch Test
    style: small
    anchor_y: top
    x: center
    y: top
  - type: text
    text: "Last: (switch_name)"
    style: small
    y: center
  - type: text
    text: (switch_state)
    style: small
    anchor_y: bottom
    y: bottom


widgets:
  service_power_off_door_open:
    type: text
    text: Coil Power Off
    anchor_y: bottom
    x: center
    y: bottom+4
    style: medium
    animations:
      add_to_slide:
      - property: opacity
        value: 1
        duration: 0.5s
      - property: opacity
        value: 0
        duration: 0.5s
        repeat: true

  service_menu_item_switch:
    type: text
    text: Switch Test
    anchor_y: center
    style: medium
  service_menu_item_coil:
    type: text
    text: Coil Test
    anchor_y: center
    style: medium
  service_menu_item_settings:
    type: text
    text: Settings
    anchor_y: center
    style: medium