#config_version=4
mode:
  code: service.Service
  priority: 100000
  start_events: reset_complete
  stop_on_ball_end: False

event_player:
    sw_service_door_open_active:
        service_door_opened
    sw_service_door_open_inactive:
        service_door_closed