2:
  section_replacements:
    assetdefaults: asset_defaults
    autofire coils: autofire_coils
    balldevices: ball_devices
    ballsearch: ball_search
    droptargets: drop_targets
    droptargetbanks: drop_target_banks
    languagestrings: language_strings
    lightplayer: light_player
    lightscripts: light_scripts
    logicblocks: logic_blocks
    ledsettings: led_settings
    machineflow: machine_flow
    machineflow_attract_start: attract_start
    machineflow_attract_stop: attract_stop
    matrixlights: matrix_lights
    mediacontroller: media_controller
    openpixelcontrol: open_pixel_control
    score reels: score_reels
    score reel groups: score_reel_groups
    showplayer: show_player
    slideplayer: slide_player
    soundplayer: sound_player
    soundsystem: sound_system
    switchplayer: switch_player
    targetgroups: target_groups
    virtual platform start active switches: virtual_platform_start_active_switches

  section_warnings:
    - path: targets
      url: "https://missionpinball.com/docs/configuration-file-reference/targets/"
    - path: target_groups
      url: "https://missionpinball.com/docs/configuration-file-reference/targetgroups/"
    - path: drop_targets
      url: "https://missionpinball.com/docs/configuration-file-reference/droptargets/"
    - path: drop_target_banks
      url: "https://missionpinball.com/docs/configuration-file-reference/droptargetbanks/"

  section_deprecations:
    - plugins

# Below is a list of things we'll change in v3, but we don't want to do that
# until we have enough to warrant an actual change.

#3:
#  section_replacements:
#    balls installed: balls_installed
#    min balls: min_balls
#    max balls: max_balls
#    balls per game: balls_per_game
#    max players per game: max_players