name: Wheel Builder

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.cibw-build }}
    runs-on: ${{ matrix.os }}
    strategy:  
      fail-fast: false
      matrix:
        include:
        - os: windows-latest
          python-version: 3.8
          cibw-build: cp38-win_amd64
        - os: windows-latest
          python-version: 3.9
          cibw-build: cp39-win_amd64
        - os: ubuntu-latest
          python-version: 3.8
          cibw-build: cp38-manylinux_x86_64
        - os: ubuntu-latest
          python-version: 3.9
          cibw-build: cp39-manylinux_x86_64
        # - os: macos-latest     # Github hosted and self-hosted ARM runners are not yet available, so I'll just build locally for now.
        #   python-version: 3.8
        #   cibw-build: cp38-macosx_arm64
        # - os: macos-latest
        #   python-version: 3.9
        #   cibw-build: cp39-macosx_arm64
        - os: macos-latest
          python-version: 3.8
          cibw-build: cp38-macosx_x86_64
        - os: macos-latest
          python-version: 3.9
          cibw-build: cp39-macosx_x86_64

    steps:
      - name: Checkout MPF
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run cibuildwheel
        uses: pypa/cibuildwheel@v2.8.1
        env:
          CIBW_BUILD: ${{ matrix.cibw-build }}
          CIBW_BUILD_VERBOSITY: 3

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl